/*
 * generated by Xtext 2.19.0
 */
package org.sa.rainbow.configuration.ide

/**
 * Use this class to register ide components.
 */
class ConfigModelIdeModule extends AbstractConfigModelIdeModule {
	
//	override configure(Binder binder) {
//		super.configure(binder)
//	}
	
}
