/*
 * generated by Xtext 2.19.0
 */
package org.acme

import org.acme.scoping.QualifiedNameProvider
import org.acme.scoping.AcmeScopeProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AcmeRuntimeModule extends AbstractAcmeRuntimeModule {
	
	override bindIQualifiedNameProvider() {
		QualifiedNameProvider
	}
	
	override bindIScopeProvider() {
		AcmeScopeProvider
	}
	
}
