package org.sa.rainbow.core;

public enum RainbowComponentT {
    DELEGATE, MASTER, PROBE, GAUGE, MODEL, ANALYSIS, SELECTOR, EXECUTOR, EFFECTOR, GAUGE_MANAGER, PROBE_MANAGER, EFFECTOR_MANAGER, ADAPTATION_MANAGER
}
