/*
 * generated by Xtext 2.19.0
 */
package org.acme.ide

import com.google.inject.Guice
import org.acme.AcmeRuntimeModule
import org.acme.AcmeStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AcmeIdeSetup extends AcmeStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AcmeRuntimeModule, new AcmeIdeModule))
	}
	
}
