/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.alexmerz.graphviz;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EDGE_DIRECTED = 9;
  /** RegularExpression Id. */
  int EDGE_UNDIRECTED = 10;
  /** RegularExpression Id. */
  int SEMI = 11;
  /** RegularExpression Id. */
  int DOUBLE = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int EQUAL = 14;
  /** RegularExpression Id. */
  int SPACE = 15;
  /** RegularExpression Id. */
  int LBRACKET = 16;
  /** RegularExpression Id. */
  int RBRACKET = 17;
  /** RegularExpression Id. */
  int LBRACE = 18;
  /** RegularExpression Id. */
  int RBRACE = 19;
  /** RegularExpression Id. */
  int LB = 20;
  /** RegularExpression Id. */
  int SUBGRAPH = 21;
  /** RegularExpression Id. */
  int NODE = 22;
  /** RegularExpression Id. */
  int EDGE = 23;
  /** RegularExpression Id. */
  int DIGRAPH = 24;
  /** RegularExpression Id. */
  int GRAPH = 25;
  /** RegularExpression Id. */
  int STRICT = 26;
  /** RegularExpression Id. */
  int STRING = 27;
  /** RegularExpression Id. */
  int ID = 28;
  /** RegularExpression Id. */
  int NUMBER = 29;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_COMMENT_OL = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"/*\"",
    "<token of kind 3>",
    "\"*/\"",
    "\"//\"",
    "<token of kind 6>",
    "\"\\n\"",
    "\"\\r\"",
    "\"->\"",
    "\"--\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"=\"",
    "\" \"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<LB>",
    "\"subgraph\"",
    "\"node\"",
    "\"edge\"",
    "\"digraph\"",
    "\"graph\"",
    "\"strict\"",
    "<STRING>",
    "<ID>",
    "<NUMBER>",
  };

}
