/*
 * generated by Xtext 2.19.0
 */
package org.sa.rainbow.stitch.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class StitchUiModule extends AbstractStitchUiModule {
}
