/*
 * generated by Xtext 2.19.0
 */
package org.sa.rainbow.stitch

import com.google.inject.Guice

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StitchStandaloneSetup extends StitchStandaloneSetupGenerated {

	def static void doSetup() {
		new StitchStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
	
	override createInjector() {
		return Guice.createInjector(new StitchRuntimeStandaloneModule)
	}
	
	
	
}
